export const CALENDAR_NAVIGATION = {
  PREVIOUS: 'PREV',
  NEXT: 'NEXT',
  TODAY: 'TODAY',
  DATE: 'DATE',
}

export const CALENDAR_DAY_AVAILABILITY = {
  EMPTY: 'EMPTY',
  REST: 'REST',
  BUSY: 'BUSY',
  LOADED: 'LOADED',
}

export const AVAILABILITY_BG_COLORS = {
  [CALENDAR_DAY_AVAILABILITY.EMPTY]: '#fff',
  [CALENDAR_DAY_AVAILABILITY.REST]: '#ddd',
  [CALENDAR_DAY_AVAILABILITY.BUSY]: '#ffff0066',
  [CALENDAR_DAY_AVAILABILITY.LOADED]: '#ff000066',
}
